-- Philippine Payroll System Database Schema
-- PostgreSQL Database

-- Create schema
CREATE SCHEMA IF NOT EXISTS payroll;

-- Set search path
SET search_path TO payroll, public;

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================
-- EMPLOYEE MANAGEMENT
-- ============================================

CREATE TABLE employees (
    employee_id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    employee_number VARCHAR(20) UNIQUE NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    middle_name VARCHAR(100),
    last_name VARCHAR(100) NOT NULL,
    suffix VARCHAR(10),
    date_of_birth DATE NOT NULL,
    gender CHAR(1) CHECK (gender IN ('M', 'F')),
    civil_status VARCHAR(20),
    
    -- Contact Information
    email VARCHAR(100),
    mobile_number VARCHAR(20),
    address TEXT,
    city VARCHAR(100),
    province VARCHAR(100),
    postal_code VARCHAR(10),
    
    -- Employment Details
    date_hired DATE NOT NULL,
    date_regularized DATE,
    date_separated DATE,
    employment_status VARCHAR(20) CHECK (employment_status IN ('Active', 'Resigned', 'Terminated', 'Retired')),
    employee_type VARCHAR(20) CHECK (employee_type IN ('Regular', 'Probationary', 'Project-Based', 'Contractual')),
    
    -- Government IDs
    sss_number VARCHAR(20),
    philhealth_number VARCHAR(20),
    pagibig_number VARCHAR(20),
    tin_number VARCHAR(20),
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by UUID,
    updated_by UUID
);

CREATE INDEX idx_employees_status ON employees(employment_status);
CREATE INDEX idx_employees_number ON employees(employee_number);
CREATE INDEX idx_employees_tin ON employees(tin_number);

-- ============================================
-- ORGANIZATION STRUCTURE
-- ============================================

CREATE TABLE departments (
    department_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_code VARCHAR(20) UNIQUE NOT NULL,
    department_name VARCHAR(100) NOT NULL,
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE positions (
    position_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position_code VARCHAR(20) UNIQUE NOT NULL,
    position_title VARCHAR(100) NOT NULL,
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE employee_assignments (
    assignment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id UUID REFERENCES employees(employee_id),
    department_id INTEGER REFERENCES departments(department_id),
    position_id INTEGER REFERENCES positions(position_id),
    is_primary BOOLEAN DEFAULT TRUE,
    effective_date DATE NOT NULL,
    end_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- COMPENSATION AND BENEFITS
-- ============================================

CREATE TABLE salary_grades (
    salary_grade_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grade_code VARCHAR(20) UNIQUE NOT NULL,
    grade_name VARCHAR(100) NOT NULL,
    min_salary NUMERIC(15, 2) NOT NULL,
    max_salary NUMERIC(15, 2) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE
);

CREATE TABLE employee_compensation (
    compensation_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id UUID REFERENCES employees(employee_id),
    salary_grade_id INTEGER REFERENCES salary_grades(salary_grade_id),
    
    -- Basic Pay
    basic_salary NUMERIC(15, 2) NOT NULL,
    daily_rate NUMERIC(15, 2),
    hourly_rate NUMERIC(15, 2),
    
    -- Pay Frequency
    pay_frequency VARCHAR(20) CHECK (pay_frequency IN ('Monthly', 'Semi-Monthly', 'Weekly', 'Daily')),
    
    -- Other Regular Pay
    cola NUMERIC(15, 2) DEFAULT 0, -- Cost of Living Allowance
    
    effective_date DATE NOT NULL,
    end_date DATE,
    is_active BOOLEAN DEFAULT TRUE,
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by UUID
);

CREATE TABLE allowances (
    allowance_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    allowance_code VARCHAR(20) UNIQUE NOT NULL,
    allowance_name VARCHAR(100) NOT NULL,
    description TEXT,
    is_taxable BOOLEAN DEFAULT TRUE,
    is_active BOOLEAN DEFAULT TRUE
);

CREATE TABLE employee_allowances (
    employee_allowance_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id UUID REFERENCES employees(employee_id),
    allowance_id INTEGER REFERENCES allowances(allowance_id),
    amount NUMERIC(15, 2) NOT NULL,
    frequency VARCHAR(20) CHECK (frequency IN ('Monthly', 'Per-Payroll', 'Daily', 'One-Time')),
    effective_date DATE NOT NULL,
    end_date DATE,
    is_active BOOLEAN DEFAULT TRUE
);

-- ============================================
-- TIME AND ATTENDANCE
-- ============================================

CREATE TABLE attendance (
    attendance_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id UUID REFERENCES employees(employee_id),
    attendance_date DATE NOT NULL,
    
    -- Time In/Out
    time_in TIMESTAMP,
    time_out TIMESTAMP,
    
    -- Break Times
    break_out TIMESTAMP,
    break_in TIMESTAMP,
    
    -- Computed Hours
    regular_hours NUMERIC(5, 2) DEFAULT 0,
    overtime_hours NUMERIC(5, 2) DEFAULT 0,
    late_minutes INTEGER DEFAULT 0,
    undertime_minutes INTEGER DEFAULT 0,
    
    -- Status
    is_holiday BOOLEAN DEFAULT FALSE,
    is_rest_day BOOLEAN DEFAULT FALSE,
    is_absent BOOLEAN DEFAULT FALSE,
    
    remarks TEXT,
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    UNIQUE(employee_id, attendance_date)
);

CREATE INDEX idx_attendance_employee_date ON attendance(employee_id, attendance_date);

-- ============================================
-- LEAVE MANAGEMENT
-- ============================================

CREATE TABLE leave_types (
    leave_type_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leave_code VARCHAR(20) UNIQUE NOT NULL,
    leave_name VARCHAR(100) NOT NULL,
    description TEXT,
    is_paid BOOLEAN DEFAULT TRUE,
    is_active BOOLEAN DEFAULT TRUE
);

CREATE TABLE employee_leaves (
    leave_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id UUID REFERENCES employees(employee_id),
    leave_type_id INTEGER REFERENCES leave_types(leave_type_id),
    
    leave_date_from DATE NOT NULL,
    leave_date_to DATE NOT NULL,
    number_of_days NUMERIC(5, 2) NOT NULL,
    
    reason TEXT,
    status VARCHAR(20) CHECK (status IN ('Pending', 'Approved', 'Rejected', 'Cancelled')),
    
    approved_by UUID,
    approved_date TIMESTAMP,
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by UUID
);

-- ============================================
-- PHILIPPINE GOVERNMENT CONTRIBUTIONS
-- ============================================

-- SSS (Social Security System) Contribution Table
CREATE TABLE sss_contribution_table (
    sss_table_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    min_salary NUMERIC(15, 2) NOT NULL,
    max_salary NUMERIC(15, 2) NOT NULL,
    employee_contribution NUMERIC(15, 2) NOT NULL,
    employer_contribution NUMERIC(15, 2) NOT NULL,
    total_contribution NUMERIC(15, 2) NOT NULL,
    ec_contribution NUMERIC(15, 2) DEFAULT 0, -- Employees' Compensation
    effective_date DATE NOT NULL,
    end_date DATE,
    is_active BOOLEAN DEFAULT TRUE
);

-- PhilHealth Contribution Table
CREATE TABLE philhealth_contribution_table (
    philhealth_table_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    min_salary NUMERIC(15, 2) NOT NULL,
    max_salary NUMERIC(15, 2),
    premium_rate NUMERIC(5, 4) NOT NULL, -- e.g., 0.05 for 5%
    employee_share NUMERIC(5, 4) NOT NULL, -- e.g., 0.50 for 50%
    employer_share NUMERIC(5, 4) NOT NULL, -- e.g., 0.50 for 50%
    effective_date DATE NOT NULL,
    end_date DATE,
    is_active BOOLEAN DEFAULT TRUE
);

-- Pag-IBIG Contribution Table
CREATE TABLE pagibig_contribution_table (
    pagibig_table_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    min_salary NUMERIC(15, 2) NOT NULL,
    max_salary NUMERIC(15, 2),
    employee_rate NUMERIC(5, 4) NOT NULL, -- e.g., 0.02 for 2%
    employer_rate NUMERIC(5, 4) NOT NULL, -- e.g., 0.02 for 2%
    max_employee_contribution NUMERIC(15, 2),
    max_employer_contribution NUMERIC(15, 2),
    effective_date DATE NOT NULL,
    end_date DATE,
    is_active BOOLEAN DEFAULT TRUE
);

-- Tax (BIR) Withholding Table
CREATE TABLE tax_table (
    tax_table_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    min_compensation NUMERIC(15, 2) NOT NULL,
    max_compensation NUMERIC(15, 2),
    base_tax NUMERIC(15, 2) NOT NULL,
    tax_rate NUMERIC(5, 4) NOT NULL, -- e.g., 0.20 for 20%
    excess_over NUMERIC(15, 2) NOT NULL,
    
    -- Tax period
    period_type VARCHAR(20) CHECK (period_type IN ('Annual', 'Monthly', 'Semi-Monthly', 'Weekly', 'Daily')),
    
    effective_date DATE NOT NULL,
    end_date DATE,
    is_active BOOLEAN DEFAULT TRUE
);

-- ============================================
-- PAYROLL PROCESSING
-- ============================================

CREATE TABLE payroll_periods (
    payroll_period_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_name VARCHAR(100) NOT NULL,
    period_type VARCHAR(20) CHECK (period_type IN ('Monthly', 'Semi-Monthly', 'Weekly', 'Special')),
    
    period_start_date DATE NOT NULL,
    period_end_date DATE NOT NULL,
    payment_date DATE NOT NULL,
    
    cutoff_date DATE,
    
    status VARCHAR(20) CHECK (status IN ('Draft', 'Processing', 'Completed', 'Posted', 'Cancelled')) DEFAULT 'Draft',
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by UUID,
    processed_at TIMESTAMP,
    processed_by UUID
);

CREATE TABLE payroll_headers (
    payroll_header_id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    payroll_period_id INTEGER REFERENCES payroll_periods(payroll_period_id),
    employee_id UUID REFERENCES employees(employee_id),
    
    -- Basic Information
    basic_salary NUMERIC(15, 2) NOT NULL,
    daily_rate NUMERIC(15, 2),
    hourly_rate NUMERIC(15, 2),
    
    -- Hours Worked
    regular_hours NUMERIC(10, 2) DEFAULT 0,
    overtime_hours NUMERIC(10, 2) DEFAULT 0,
    holiday_hours NUMERIC(10, 2) DEFAULT 0,
    rest_day_hours NUMERIC(10, 2) DEFAULT 0,
    
    -- Days
    days_worked NUMERIC(5, 2) DEFAULT 0,
    days_absent NUMERIC(5, 2) DEFAULT 0,
    days_leave NUMERIC(5, 2) DEFAULT 0,
    
    -- Gross Pay Components
    basic_pay NUMERIC(15, 2) DEFAULT 0,
    overtime_pay NUMERIC(15, 2) DEFAULT 0,
    holiday_pay NUMERIC(15, 2) DEFAULT 0,
    night_differential NUMERIC(15, 2) DEFAULT 0,
    
    -- Other Income
    total_allowances NUMERIC(15, 2) DEFAULT 0,
    total_bonuses NUMERIC(15, 2) DEFAULT 0,
    total_adjustments NUMERIC(15, 2) DEFAULT 0,
    
    -- Gross Calculation
    gross_pay NUMERIC(15, 2) DEFAULT 0,
    
    -- Deductions
    sss_contribution NUMERIC(15, 2) DEFAULT 0,
    philhealth_contribution NUMERIC(15, 2) DEFAULT 0,
    pagibig_contribution NUMERIC(15, 2) DEFAULT 0,
    withholding_tax NUMERIC(15, 2) DEFAULT 0,
    
    total_loans NUMERIC(15, 2) DEFAULT 0,
    total_other_deductions NUMERIC(15, 2) DEFAULT 0,
    
    -- Net Calculation
    total_deductions NUMERIC(15, 2) DEFAULT 0,
    net_pay NUMERIC(15, 2) DEFAULT 0,
    
    -- Status
    status VARCHAR(20) CHECK (status IN ('Draft', 'Computed', 'Approved', 'Paid', 'Cancelled')) DEFAULT 'Draft',
    
    remarks TEXT,
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by UUID,
    approved_at TIMESTAMP,
    approved_by UUID
);

CREATE INDEX idx_payroll_header_period ON payroll_headers(payroll_period_id);
CREATE INDEX idx_payroll_header_employee ON payroll_headers(employee_id);

-- Payroll Earnings (Detailed)
CREATE TABLE payroll_earnings (
    payroll_earning_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payroll_header_id UUID REFERENCES payroll_headers(payroll_header_id),
    
    earning_type VARCHAR(50) NOT NULL, -- 'Basic', 'Overtime', 'Holiday', 'Allowance', 'Bonus', etc.
    earning_code VARCHAR(20),
    description VARCHAR(200),
    
    quantity NUMERIC(10, 2), -- hours, days, or units
    rate NUMERIC(15, 2),
    amount NUMERIC(15, 2) NOT NULL,
    
    is_taxable BOOLEAN DEFAULT TRUE,
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Payroll Deductions (Detailed)
CREATE TABLE payroll_deductions (
    payroll_deduction_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payroll_header_id UUID REFERENCES payroll_headers(payroll_header_id),
    
    deduction_type VARCHAR(50) NOT NULL, -- 'SSS', 'PhilHealth', 'PagIBIG', 'Tax', 'Loan', 'Other'
    deduction_code VARCHAR(20),
    description VARCHAR(200),
    
    amount NUMERIC(15, 2) NOT NULL,
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- LOANS AND DEDUCTIONS
-- ============================================

CREATE TABLE loan_types (
    loan_type_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_code VARCHAR(20) UNIQUE NOT NULL,
    loan_name VARCHAR(100) NOT NULL,
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE
);

CREATE TABLE employee_loans (
    loan_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id UUID REFERENCES employees(employee_id),
    loan_type_id INTEGER REFERENCES loan_types(loan_type_id),
    
    loan_amount NUMERIC(15, 2) NOT NULL,
    interest_rate NUMERIC(5, 4) DEFAULT 0,
    number_of_installments INTEGER NOT NULL,
    monthly_amortization NUMERIC(15, 2) NOT NULL,
    
    loan_date DATE NOT NULL,
    first_deduction_date DATE NOT NULL,
    
    total_paid NUMERIC(15, 2) DEFAULT 0,
    balance NUMERIC(15, 2),
    
    status VARCHAR(20) CHECK (status IN ('Active', 'Completed', 'Cancelled')) DEFAULT 'Active',
    
    remarks TEXT,
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by UUID
);

CREATE TABLE loan_payments (
    payment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_id INTEGER REFERENCES employee_loans(loan_id),
    payroll_header_id UUID REFERENCES payroll_headers(payroll_header_id),
    
    payment_date DATE NOT NULL,
    principal_amount NUMERIC(15, 2) NOT NULL,
    interest_amount NUMERIC(15, 2) DEFAULT 0,
    total_amount NUMERIC(15, 2) NOT NULL,
    
    balance_after_payment NUMERIC(15, 2),
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE other_deduction_types (
    deduction_type_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deduction_code VARCHAR(20) UNIQUE NOT NULL,
    deduction_name VARCHAR(100) NOT NULL,
    description TEXT,
    is_recurring BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE
);

CREATE TABLE employee_other_deductions (
    other_deduction_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id UUID REFERENCES employees(employee_id),
    deduction_type_id INTEGER REFERENCES other_deduction_types(deduction_type_id),
    
    amount NUMERIC(15, 2) NOT NULL,
    frequency VARCHAR(20) CHECK (frequency IN ('One-Time', 'Monthly', 'Per-Payroll')),
    
    effective_date DATE NOT NULL,
    end_date DATE,
    
    is_active BOOLEAN DEFAULT TRUE,
    remarks TEXT
);

-- ============================================
-- HOLIDAYS
-- ============================================

CREATE TABLE holidays (
    holiday_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    holiday_name VARCHAR(100) NOT NULL,
    holiday_date DATE NOT NULL,
    holiday_type VARCHAR(20) CHECK (holiday_type IN ('Regular', 'Special Non-Working', 'Special Working')) NOT NULL,
    
    -- Premium rates
    regular_day_premium NUMERIC(5, 4) DEFAULT 2.0, -- 200% for regular holiday
    rest_day_premium NUMERIC(5, 4) DEFAULT 2.6, -- 260% for regular holiday on rest day
    
    year INTEGER NOT NULL,
    is_recurring BOOLEAN DEFAULT FALSE, -- If it recurs every year
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_holidays_date ON holidays(holiday_date);
CREATE INDEX idx_holidays_year ON holidays(year);

-- ============================================
-- AUDIT TRAIL
-- ============================================

CREATE TABLE audit_logs (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name VARCHAR(100) NOT NULL,
    record_id VARCHAR(50) NOT NULL,
    action VARCHAR(20) CHECK (action IN ('INSERT', 'UPDATE', 'DELETE')) NOT NULL,
    
    old_values JSONB,
    new_values JSONB,
    
    changed_by UUID,
    changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    ip_address VARCHAR(50),
    user_agent TEXT
);

CREATE INDEX idx_audit_table_record ON audit_logs(table_name, record_id);
CREATE INDEX idx_audit_changed_at ON audit_logs(changed_at);

-- ============================================
-- USERS AND SECURITY
-- ============================================

CREATE TABLE users (
    user_id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    role VARCHAR(20) NOT NULL DEFAULT 'Employee' CHECK (role IN ('Admin', 'HR', 'Employee')),
    
    employee_id UUID REFERENCES employees(employee_id),
    
    is_active BOOLEAN DEFAULT TRUE,
    last_login TIMESTAMP,
    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE roles (
    role_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(50) UNIQUE NOT NULL,
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE
);

CREATE TABLE user_roles (
    user_role_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES users(user_id),
    role_id INTEGER REFERENCES roles(role_id),
    
    granted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    granted_by UUID,
    
    UNIQUE(user_id, role_id)
);

-- ============================================
-- INITIAL DATA INSERTS
-- ============================================

-- Insert default leave types
INSERT INTO leave_types (leave_code, leave_name, description, is_paid) VALUES
('VL', 'Vacation Leave', 'Paid vacation leave', TRUE),
('SL', 'Sick Leave', 'Paid sick leave', TRUE),
('ML', 'Maternity Leave', 'Maternity leave', TRUE),
('PL', 'Paternity Leave', 'Paternity leave', TRUE),
('EL', 'Emergency Leave', 'Emergency leave', TRUE),
('LWOP', 'Leave Without Pay', 'Unpaid leave', FALSE);

-- Insert default allowance types
INSERT INTO allowances (allowance_code, allowance_name, is_taxable) VALUES
('TRANS', 'Transportation Allowance', FALSE),
('MEAL', 'Meal Allowance', FALSE),
('COMM', 'Communication Allowance', TRUE),
('HOUSING', 'Housing Allowance', TRUE),
('CLOTH', 'Clothing Allowance', TRUE);

-- Insert default loan types
INSERT INTO loan_types (loan_code, loan_name) VALUES
('SSS', 'SSS Loan'),
('PAGIBIG', 'Pag-IBIG Loan'),
('COMPANY', 'Company Loan'),
('SALARY', 'Salary Loan'),
('EMERGENCY', 'Emergency Loan');

-- Insert default other deduction types
INSERT INTO other_deduction_types (deduction_code, deduction_name, is_recurring) VALUES
('TARDINESS', 'Tardiness Deduction', FALSE),
('UNDERTIME', 'Undertime Deduction', FALSE),
('ABSENCE', 'Absence Deduction', FALSE),
('UNIFORM', 'Uniform Deduction', TRUE),
('CASH_ADVANCE', 'Cash Advance', FALSE);

-- Insert default roles
INSERT INTO roles (role_name, description) VALUES
('Administrator', 'Full system access'),
('Payroll Manager', 'Manage payroll operations'),
('HR Manager', 'Manage employee records'),
('Department Manager', 'View department reports'),
('Employee', 'View own payroll information');

-- Insert Philippine holidays for 2026
INSERT INTO holidays (holiday_name, holiday_date, holiday_type, year, is_recurring) VALUES
('New Year''s Day', '2026-01-01', 'Regular', 2026, TRUE),
('EDSA Revolution Anniversary', '2026-02-25', 'Special Non-Working', 2026, TRUE),
('Maundy Thursday', '2026-04-02', 'Regular', 2026, FALSE),
('Good Friday', '2026-04-03', 'Regular', 2026, FALSE),
('Araw ng Kagitingan', '2026-04-09', 'Regular', 2026, TRUE),
('Labor Day', '2026-05-01', 'Regular', 2026, TRUE),
('Independence Day', '2026-06-12', 'Regular', 2026, TRUE),
('Ninoy Aquino Day', '2026-08-21', 'Special Non-Working', 2026, TRUE),
('National Heroes Day', '2026-08-31', 'Regular', 2026, FALSE),
('All Saints'' Day', '2026-11-01', 'Special Non-Working', 2026, TRUE),
('Bonifacio Day', '2026-11-30', 'Regular', 2026, TRUE),
('Feast of the Immaculate Conception', '2026-12-08', 'Special Non-Working', 2026, TRUE),
('Christmas Day', '2026-12-25', 'Regular', 2026, TRUE),
('Rizal Day', '2026-12-30', 'Regular', 2026, TRUE),
('New Year''s Eve', '2026-12-31', 'Special Non-Working', 2026, TRUE);

-- ============================================
-- VIEWS FOR REPORTING
-- ============================================

-- View: Current Employee Compensation
CREATE OR REPLACE VIEW vw_current_employee_compensation AS
SELECT 
    e.employee_id,
    e.employee_number,
    e.first_name,
    e.last_name,
    ec.basic_salary,
    ec.daily_rate,
    ec.hourly_rate,
    ec.pay_frequency,
    ec.cola,
    sg.grade_name as salary_grade
FROM employees e
LEFT JOIN employee_compensation ec ON e.employee_id = ec.employee_id AND ec.is_active = TRUE
LEFT JOIN salary_grades sg ON ec.salary_grade_id = sg.salary_grade_id
WHERE e.employment_status = 'Active';

-- View: Employee with Department and Position
CREATE OR REPLACE VIEW vw_employee_details AS
SELECT 
    e.employee_id,
    e.employee_number,
    e.first_name,
    e.middle_name,
    e.last_name,
    e.email,
    e.mobile_number,
    e.employment_status,
    e.employee_type,
    d.department_name,
    p.position_title,
    e.date_hired,
    e.sss_number,
    e.philhealth_number,
    e.pagibig_number,
    e.tin_number
FROM employees e
LEFT JOIN employee_assignments ea ON e.employee_id = ea.employee_id AND ea.is_primary = TRUE AND ea.end_date IS NULL
LEFT JOIN departments d ON ea.department_id = d.department_id
LEFT JOIN positions p ON ea.position_id = p.position_id;

-- View: Active Loans Summary
CREATE OR REPLACE VIEW vw_active_loans AS
SELECT 
    e.employee_id,
    e.employee_number,
    e.first_name,
    e.last_name,
    lt.loan_name,
    el.loan_amount,
    el.monthly_amortization,
    el.total_paid,
    el.balance,
    el.loan_date,
    el.status
FROM employee_loans el
JOIN employees e ON el.employee_id = e.employee_id
JOIN loan_types lt ON el.loan_type_id = lt.loan_type_id
WHERE el.status = 'Active';

COMMENT ON SCHEMA payroll IS 'Philippine Payroll System Schema';
COMMENT ON TABLE employees IS 'Core employee information';
COMMENT ON TABLE payroll_headers IS 'Main payroll computation per employee per period';
COMMENT ON TABLE sss_contribution_table IS 'SSS contribution matrix based on monthly salary';
COMMENT ON TABLE philhealth_contribution_table IS 'PhilHealth premium computation table';
COMMENT ON TABLE pagibig_contribution_table IS 'Pag-IBIG contribution computation table';
COMMENT ON TABLE tax_table IS 'BIR withholding tax table (TRAIN Law)';
